name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          cache: true

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Run tests
        run: cargo test --all-features

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Build release
        run: cargo build --release

      - name: Set Windows artifact names
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          "ARTIFACT_NAME=deck_cli-windows.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "BINARY_PATH=target/release/deck_cli.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set macOS artifact names
        if: matrix.os == 'macos-latest'
        run: |
          echo "ARTIFACT_NAME=deck_cli-macos" >> $GITHUB_ENV
          echo "BINARY_PATH=target/release/deck_cli" >> $GITHUB_ENV

      - name: Set Linux artifact names
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "ARTIFACT_NAME=deck_cli-linux" >> $GITHUB_ENV
          echo "BINARY_PATH=target/release/deck_cli" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BINARY_PATH }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -la ./artifacts/

      - name: Rename binaries for release
        run: |
          mv ./artifacts/deck_cli-linux/deck_cli ./artifacts/deck_cli-linux
          mv ./artifacts/deck_cli-macos/deck_cli ./artifacts/deck_cli-macos
          mv ./artifacts/deck_cli-windows.exe/deck_cli.exe ./artifacts/deck_cli-windows.exe
          rm -rf ./artifacts/deck_cli-linux/
          rm -rf ./artifacts/deck_cli-macos/
          rm -rf ./artifacts/deck_cli-windows.exe/
          ls -la ./artifacts/

      - name: Generate release tag
        id: tag
        run: |
          echo "tag=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            Automated release for commit ${{ github.sha }}

            ## Changes
            - Latest changes from main branch

            ## Downloads
            - Linux: deck_cli-linux
            - macOS: deck_cli-macos  
            - Windows: deck_cli-windows.exe
          files: |
            ./artifacts/deck_cli-linux
            ./artifacts/deck_cli-macos
            ./artifacts/deck_cli-windows.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
